### ISSUE TITLE
NPE when no sets are present

### ISSUE THREAD

**Issue by jangalinski** [holisticon/ranked#12]
somehow, the sets are evaluated after the disjunct validation, which leads to NPE in the disjunct function

```
java.lang.NullPointerException: null
	at de.holisticon.ranked.command.api.CreateMatch$$EQbwrayu.disjunct(Commands.kt:53) ~[na:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springsource.loaded.ri.ReloadedTypeInvoker$2.invoke(ReloadedTypeInvoker.java:133) ~[springloaded-1.2.8.RELEASE.jar:1.2.8.RELEASE]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1462) ~[springloaded-1.2.8.RELEASE.jar:1.2.8.RELEASE]
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:120) ~[spring-expression-5.0.1.RELEASE.jar:5.0.1.RELEASE]

```

**Comment by jangalinski** [comment]
fixed
